service: wing

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    API_URL: ${file(./config/environment.${opt:stage, self:provider.stage, 'dev'}.json):API_URL}
    AUTH0_WEB_CLIENT_ID: ${file(./config/secrets.${opt:stage, self:provider.stage, 'dev'}.json):AUTH0_WEB_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./config/auth0_${opt:stage, self:provider.stage, 'dev'}_publickey)}
  apiGateway:
    shouldStartNameWithService: true

functions:
  webAuth:
    handler: auth/auth.webAuth
  machineAuth:
    handler: auth/auth.machineAuth
  addProfile:
    handler: profile/profile.add
    events:
      - http:
          path: api/profile/add
          method: post
          authorizer: machineAuth
          cors: true
  updateProfile:
    handler: profile/profile.update
    events:
      - http:
          path: api/profile/update
          method: post
          authorizer: webAuth
          cors: true

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: Profiles-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'